# Generated by Django 4.0 on 2023-05-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pass_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
