# Generated by Django 4.1.3 on 2023-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_sms_code_try',
            field=models.CharField(default=3, max_length=2),
        ),
    ]
