# Generated by Django 4.1.3 on 2023-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_max_sms_code_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_code_max_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
