# Generated by Django 4.1.3 on 2023-04-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_sms_code_max_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
